# Generated by Django 5.0.6 on 2024-06-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_data',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=100, null=True)),
                ('password', models.TextField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Registration',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Phonenumber', models.BigIntegerField(null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Password', models.TextField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('work', models.TextField(max_length=10000, null=True)),
                ('Created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.login_data')),
            ],
        ),
    ]
