# Generated by Django 5.0.6 on 2024-06-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='Submit_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='works',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
