# Generated by Django 5.0.6 on 2024-06-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_works_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='Submit_time',
            field=models.DateField(null=True),
        ),
    ]
