# Generated by Django 5.0.6 on 2024-07-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_works_submit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='works',
            name='To',
        ),
        migrations.DeleteModel(
            name='User_Registration',
        ),
        migrations.DeleteModel(
            name='Login_data',
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
